# Generated by Django 6.0.5 on 2026-05-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
